DROP DATABASE IF EXISTS `juanmartin_m3`;

CREATE DATABASE `juanmartin_m3` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;

USE `juanmartin_m3`;

CREATE TABLE `ESPECIALIDADES` (
       `idespecialidad` SMALLINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
       `descripcion` VARCHAR(25) NOT NULL
);


CREATE TABLE `TRABAJOS` (
       `idtrabajo` SMALLINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
       `idespecialidad` SMALLINT UNSIGNED NOT NULL,
       `anno` YEAR NOT NULL,
       `empresa` VARCHAR(25) NOT NULL,
       `tareas` VARCHAR(100) NOT NULL,
       `meritos` VARCHAR(100) NOT NULL,
       CONSTRAINT `fk_trabajos_especialidades` FOREIGN KEY (`idespecialidad`) REFERENCES `ESPECIALIDADES` (`idespecialidad`)
);


CREATE TABLE `BLOG` (
       `idblog` INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
       `fecha` DATE NOT NULL,
       `titulo` VARCHAR(50) NOT NULL,
       `contenido` TEXT NOT NULL,
       `imagen` VARCHAR(255) NOT NULL
);


INSERT INTO ESPECIALIDADES (descripcion) VALUES ("Programacion"),("Diseño de Aplicaciones"),("Gestion de Proyectos");

INSERT INTO TRABAJOS
       (idespecialidad, anno, empresa, tareas, meritos)
VALUES
        (1, 1990, "En la primera", "Era un S34 de IBM", "Sobrevivir"),
        (1, 1992, "En la segunda", "Era un S38 de IBM", "Sobrevivir, juerga, cachondeo y sopa boba"),
        (2, 1994, "En la tercera", "Era para el gobierno", "Por fin senior"),
        (2, 1999, "Casi en casa", "Efecto 2000, Euro", "No haber matado a nadie en el proceso, Jefe de Proyectos"),
        (3, 2001, "Con un colega", "Jefe de Proyectos", "Ninguno, se me escapo vivo");


INSERT INTO BLOG
       (fecha, titulo, contenido, imagen)
VALUES
        (CURRENT_DATE(), "Ejemplo 1", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam tristique feugiat lectus. Nulla sapien nibh, gravida at pharetra ut, tristique in metus. Pellentesque in interdum ex, at tincidunt est. Quisque lectus tortor, condimentum ac leo et, efficitur tincidunt sem. Ut sed efficitur nisi. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; In ornare tincidunt accumsan. Donec et varius ex, et dignissim nibh. Sed finibus tellus quis dui pulvinar, sed varius quam consectetur. Vestibulum quis mattis est, non interdum lorem. Ut laoreet magna eu sem finibus, ac placerat orci placerat. Ut urna nunc, elementum eget tempus ut, euismod et ligula. Curabitur metus sapien, bibendum pulvinar ultrices in, ultrices ac urna.", "imagen01.jpg"),
        ("2021-11-20", "Ejemplo 2", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam tristique feugiat lectus. Nulla sapien nibh, gravida at pharetra ut, tristique in metus. Pellentesque in interdum ex, at tincidunt est. Quisque lectus tortor, condimentum ac leo et, efficitur tincidunt sem. Ut sed efficitur nisi. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; In ornare tincidunt accumsan. Donec et varius ex, et dignissim nibh. Sed finibus tellus quis dui pulvinar, sed varius quam consectetur. Vestibulum quis mattis est, non interdum lorem. Ut laoreet magna eu sem finibus, ac placerat orci placerat.", "imagen02.jpg"),
        ("2021-11-19", "Ejemplo 3", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam tristique feugiat lectus. Nulla sapien nibh, gravida at pharetra ut, tristique in metus. Pellentesque in interdum ex, at tincidunt est. Quisque lectus tortor, condimentum ac leo et, efficitur tincidunt sem. Ut sed efficitur nisi. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; In ornare tincidunt accumsan. s ut, euismod et ligula. Curabitur metus sapien, bibendum pulvinar ultrices in, ultrices ac urna.", "imagen03.jpg"),
        ("2021-11-18", "Ejemplo 4", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam tristique feugiat lectus. Nulla sapien nibh, gravida at pharetra ut, tristique in metus. Pellentesque in interdum ex, at tincidunt est. Quisque lectus tortor, condimentum ac leo et, efficitur tincidunt sem. Ut sed efficitur nisi. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; In ornare tincidunt accumsan. Donec et varius ex, et dignissim nibh. Sed finibus tellus quis dui pulvinar, sed varius quam consectetur. Vestibulum quis mattis est, non interdum lorem. Ut laoreet magna eu sem finibus, ac placerat orci placerat. Ut urna nunc, elementum eget tempus ut, euismod et ligula. Curabitur metus sapien, bibendum pulvinar ultrices in, ultrices ac urna.", "imagen04.jpg"),
        ("2021-11-17", "Ejemplo 5", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam tristique feugiat lectus. Nulla sapien nibh, gravida at pharetra ut, tristique in metus. Pellentesque in interdum ex, at tincidunt est. Quisque lectus tortor, condimentum ac leo et, efficitur tincidunt sem. Ut sed efficitur nisi. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; In ornare tincidunt accumsan. Donec et varius ex, et dignissim nibh. Sed finibus tellus quis dui pulvinar, sed varius quam consectetur. Vestibulum quis mattis est, non interdum lorem. Ut laoreet magna eu sem finibus, ac placerat orci placerat. Ut urna nunc, elementum eget tempus ut, euismod et li.", "imagen05.jpg"),
        ("2021-11-16", "Ejemplo 2", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam tristique feugiat lectus. Nulla sapien nibh, gravida at pharetra ut, tristique in metus. Pellentesque in interdum ex, at tincidunt est. Quisque lectus tortor, condimentum ac leo et, efficitur tincidunt sem. Ut sed efficitur nisi. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; In ornare tincidunt accumsan. Donec et varius ex, et dignissim nibh. Sed finibus tellus quis dui pulvinar, sed varius quam consectetur. Vestibulum quis mattis est, non interdum lorem. Ut laoreet magna eu sem finibus, ac placerat orci placerat.", "imagen02.jpg"),
        ("2021-11-15", "Ejemplo 4", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam tristique feugiat lectus. Nulla sapien nibh, gravida at pharetra ut, tristique in metus. Pellentesque in interdum ex, at tincidunt est. Quisque lectus tortor, condimentum ac leo et, efficitur tincidunt sem. Ut sed efficitur nisi. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; In ornare tincidunt accumsan. Donec et varius ex, et dignissim nibh. Sed finibus tellus quis dui pulvinar, sed varius quam consectetur. Vestibulum quis mattis est, non interdum lorem. Ut laoreet magna eu sem finibus, ac placerat orci placerat. Ut urna nunc, elementum eget tempus ut, euismod et ligula. Curabitur metus sapien, bibendum pulvinar ultrices in, ultrices ac urna.", "imagen04.jpg"),
        ("2021-11-14", "Ejemplo 1", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam tristique feugiat lectus. Nulla sapien nibh, gravida at pharetra ut, tristique in metus. Pellentesque in interdum ex, at tincidunt est. Quisque lectus tortor, condimentum ac leo et, efficitur tincidunt sem. Ut sed efficitur nisi. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; In ornare tincidunt accumsan. Donec et varius ex, et dignissim nibh. Sed finibus tellus quis dui pulvinar, sed varius quam consectetur. Vestibulum quis mattis est, non interdum lorem. Ut laoreet magna eu sem finibus, ac placerat orci placerat. Ut urna nunc, elementum eget tempus ut, euismod et ligula. Curabitur metus sapien, bibendum pulvinar ultrices in, ultrices ac urna.", "imagen01.jpg"),
        ("2021-11-13", "Ejemplo 5", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam tristique feugiat lectus. Nulla sapien nibh, gravida at pharetra ut, tristique in metus. Pellentesque in interdum ex, at tincidunt est. Quisque lectus tortor, condimentum ac leo et, efficitur tincidunt sem. Ut sed efficitur nisi. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; In ornare tincidunt accumsan. Donec et varius ex, et dignissim nibh. Sed finibus tellus quis dui pulvinar, sed varius quam consectetur. Vestibulum quis mattis est, non interdum lorem. Ut laoreet magna eu sem finibus, ac placerat orci placerat. Ut urna nunc, elementum eget tempus ut, euismod et li.", "imagen05.jpg"),
        ("2021-11-12", "Ejemplo 3", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam tristique feugiat lectus. Nulla sapien nibh, gravida at pharetra ut, tristique in metus. Pellentesque in interdum ex, at tincidunt est. Quisque lectus tortor, condimentum ac leo et, efficitur tincidunt sem. Ut sed efficitur nisi. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; In ornare tincidunt accumsan. s ut, euismod et ligula. Curabitur metus sapien, bibendum pulvinar ultrices in, ultrices ac urna.", "imagen03.jpg"),
        ("2021-11-11", "Ejemplo 1", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam tristique feugiat lectus. Nulla sapien nibh, gravida at pharetra ut, tristique in metus. Pellentesque in interdum ex, at tincidunt est. Quisque lectus tortor, condimentum ac leo et, efficitur tincidunt sem. Ut sed efficitur nisi. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; In ornare tincidunt accumsan. Donec et varius ex, et dignissim nibh. Sed finibus tellus quis dui pulvinar, sed varius quam consectetur. Vestibulum quis mattis est, non interdum lorem. Ut laoreet magna eu sem finibus, ac placerat orci placerat. Ut urna nunc, elementum eget tempus ut, euismod et ligula. Curabitur metus sapien, bibendum pulvinar ultrices in, ultrices ac urna.", "imagen01.jpg"),
        ("2021-11-10", "Ejemplo 2", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam tristique feugiat lectus. Nulla sapien nibh, gravida at pharetra ut, tristique in metus. Pellentesque in interdum ex, at tincidunt est. Quisque lectus tortor, condimentum ac leo et, efficitur tincidunt sem. Ut sed efficitur nisi. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; In ornare tincidunt accumsan. Donec et varius ex, et dignissim nibh. Sed finibus tellus quis dui pulvinar, sed varius quam consectetur. Vestibulum quis mattis est, non interdum lorem. Ut laoreet magna eu sem finibus, ac placerat orci placerat.", "imagen02.jpg"),
        ("2021-11-09", "Ejemplo 3", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam tristique feugiat lectus. Nulla sapien nibh, gravida at pharetra ut, tristique in metus. Pellentesque in interdum ex, at tincidunt est. Quisque lectus tortor, condimentum ac leo et, efficitur tincidunt sem. Ut sed efficitur nisi. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; In ornare tincidunt accumsan. s ut, euismod et ligula. Curabitur metus sapien, bibendum pulvinar ultrices in, ultrices ac urna.", "imagen03.jpg"),
        ("2021-11-08", "Ejemplo 4", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam tristique feugiat lectus. Nulla sapien nibh, gravida at pharetra ut, tristique in metus. Pellentesque in interdum ex, at tincidunt est. Quisque lectus tortor, condimentum ac leo et, efficitur tincidunt sem. Ut sed efficitur nisi. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; In ornare tincidunt accumsan. Donec et varius ex, et dignissim nibh. Sed finibus tellus quis dui pulvinar, sed varius quam consectetur. Vestibulum quis mattis est, non interdum lorem. Ut laoreet magna eu sem finibus, ac placerat orci placerat. Ut urna nunc, elementum eget tempus ut, euismod et ligula. Curabitur metus sapien, bibendum pulvinar ultrices in, ultrices ac urna.", "imagen04.jpg"),
        ("2021-11-07", "Ejemplo 5", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam tristique feugiat lectus. Nulla sapien nibh, gravida at pharetra ut, tristique in metus. Pellentesque in interdum ex, at tincidunt est. Quisque lectus tortor, condimentum ac leo et, efficitur tincidunt sem. Ut sed efficitur nisi. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; In ornare tincidunt accumsan. Donec et varius ex, et dignissim nibh. Sed finibus tellus quis dui pulvinar, sed varius quam consectetur. Vestibulum quis mattis est, non interdum lorem. Ut laoreet magna eu sem finibus, ac placerat orci placerat. Ut urna nunc, elementum eget tempus ut, euismod et li.", "imagen05.jpg"),
        ("2021-11-06", "Ejemplo 2", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam tristique feugiat lectus. Nulla sapien nibh, gravida at pharetra ut, tristique in metus. Pellentesque in interdum ex, at tincidunt est. Quisque lectus tortor, condimentum ac leo et, efficitur tincidunt sem. Ut sed efficitur nisi. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; In ornare tincidunt accumsan. Donec et varius ex, et dignissim nibh. Sed finibus tellus quis dui pulvinar, sed varius quam consectetur. Vestibulum quis mattis est, non interdum lorem. Ut laoreet magna eu sem finibus, ac placerat orci placerat.", "imagen02.jpg"),
        ("2021-11-05", "Ejemplo 4", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam tristique feugiat lectus. Nulla sapien nibh, gravida at pharetra ut, tristique in metus. Pellentesque in interdum ex, at tincidunt est. Quisque lectus tortor, condimentum ac leo et, efficitur tincidunt sem. Ut sed efficitur nisi. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; In ornare tincidunt accumsan. Donec et varius ex, et dignissim nibh. Sed finibus tellus quis dui pulvinar, sed varius quam consectetur. Vestibulum quis mattis est, non interdum lorem. Ut laoreet magna eu sem finibus, ac placerat orci placerat. Ut urna nunc, elementum eget tempus ut, euismod et ligula. Curabitur metus sapien, bibendum pulvinar ultrices in, ultrices ac urna.", "imagen04.jpg"),
        ("2021-11-04", "Ejemplo 1", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam tristique feugiat lectus. Nulla sapien nibh, gravida at pharetra ut, tristique in metus. Pellentesque in interdum ex, at tincidunt est. Quisque lectus tortor, condimentum ac leo et, efficitur tincidunt sem. Ut sed efficitur nisi. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; In ornare tincidunt accumsan. Donec et varius ex, et dignissim nibh. Sed finibus tellus quis dui pulvinar, sed varius quam consectetur. Vestibulum quis mattis est, non interdum lorem. Ut laoreet magna eu sem finibus, ac placerat orci placerat. Ut urna nunc, elementum eget tempus ut, euismod et ligula. Curabitur metus sapien, bibendum pulvinar ultrices in, ultrices ac urna.", "imagen01.jpg"),
        ("2021-11-03", "Ejemplo 5", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam tristique feugiat lectus. Nulla sapien nibh, gravida at pharetra ut, tristique in metus. Pellentesque in interdum ex, at tincidunt est. Quisque lectus tortor, condimentum ac leo et, efficitur tincidunt sem. Ut sed efficitur nisi. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; In ornare tincidunt accumsan. Donec et varius ex, et dignissim nibh. Sed finibus tellus quis dui pulvinar, sed varius quam consectetur. Vestibulum quis mattis est, non interdum lorem. Ut laoreet magna eu sem finibus, ac placerat orci placerat. Ut urna nunc, elementum eget tempus ut, euismod et li.", "imagen05.jpg"),
        ("2021-11-02", "Ejemplo 3", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam tristique feugiat lectus. Nulla sapien nibh, gravida at pharetra ut, tristique in metus. Pellentesque in interdum ex, at tincidunt est. Quisque lectus tortor, condimentum ac leo et, efficitur tincidunt sem. Ut sed efficitur nisi. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; In ornare tincidunt accumsan. s ut, euismod et ligula. Curabitur metus sapien, bibendum pulvinar ultrices in, ultrices ac urna.", "imagen03.jpg");
